/* Auto-generated. 150 core German verbs. */
window.VERBS_DATA_DE = [
  {"de": "sein", "en": ["be"], "fr": ["être"], "pt": ["ser", "estar"]},
  {"de": "haben", "en": ["have"], "fr": ["avoir"], "pt": ["ter", "haver"]},
  {"de": "werden", "en": ["become", "get", "turn into"], "fr": ["devenir"], "pt": ["tornar-se", "ficar", "virar"]},
  {"de": "können", "en": ["can", "be able to"], "fr": ["pouvoir"], "pt": ["poder", "conseguir"]},
  {"de": "müssen", "en": ["must", "have to"], "fr": ["devoir", "falloir"], "pt": ["ter que", "precisar", "dever"]},
  {"de": "sagen", "en": ["say", "tell"], "fr": ["dire"], "pt": ["dizer", "falar"]},
  {"de": "machen", "en": ["make", "do"], "fr": ["faire"], "pt": ["fazer"]},
  {"de": "geben", "en": ["give"], "fr": ["donner"], "pt": ["dar"]},
  {"de": "kommen", "en": ["come"], "fr": ["venir"], "pt": ["vir"]},
  {"de": "sollen", "en": ["should", "ought to", "be supposed to"], "fr": ["devoir"], "pt": ["dever"]},
  {"de": "wollen", "en": ["want", "want to"], "fr": ["vouloir"], "pt": ["querer"]},
  {"de": "gehen", "en": ["go", "walk"], "fr": ["aller"], "pt": ["ir", "andar", "caminhar"]},
  {"de": "wissen", "en": ["know"], "fr": ["savoir"], "pt": ["saber"]},
  {"de": "sehen", "en": ["see", "look"], "fr": ["voir"], "pt": ["ver", "enxergar"]},
  {"de": "lassen", "en": ["let", "leave", "allow"], "fr": ["laisser"], "pt": ["deixar"]},
  {"de": "stehen", "en": ["stand", "be standing"], "fr": ["être debout", "se tenir"], "pt": ["estar de pé", "ficar de pé"]},
  {"de": "finden", "en": ["find", "think"], "fr": ["trouver"], "pt": ["encontrar", "achar"]},
  {"de": "bleiben", "en": ["stay", "remain"], "fr": ["rester"], "pt": ["ficar", "permanecer"]},
  {"de": "liegen", "en": ["lie", "be located"], "fr": ["être couché", "se trouver"], "pt": ["estar deitado", "situar-se", "jazer"]},
  {"de": "heißen", "en": ["be called", "be named"], "fr": ["s'appeler"], "pt": ["chamar-se"]},
  {"de": "denken", "en": ["think"], "fr": ["penser"], "pt": ["pensar"]},
  {"de": "nehmen", "en": ["take"], "fr": ["prendre"], "pt": ["pegar", "tomar"]},
  {"de": "tun", "en": ["do"], "fr": ["faire"], "pt": ["fazer"]},
  {"de": "dürfen", "en": ["may", "be allowed to"], "fr": ["pouvoir", "avoir le droit"], "pt": ["poder", "ter permissão"]},
  {"de": "glauben", "en": ["believe", "think"], "fr": ["croire"], "pt": ["acreditar", "crer", "achar"]},
  {"de": "halten", "en": ["hold", "stop", "keep"], "fr": ["tenir", "arrêter"], "pt": ["segurar", "parar", "manter"]},
  {"de": "nennen", "en": ["name", "call"], "fr": ["nommer", "appeler"], "pt": ["chamar", "nomear"]},
  {"de": "mögen", "en": ["like"], "fr": ["aimer", "aimer bien"], "pt": ["gostar"]},
  {"de": "zeigen", "en": ["show", "point"], "fr": ["montrer"], "pt": ["mostrar"]},
  {"de": "führen", "en": ["lead", "guide"], "fr": ["mener", "conduire", "diriger"], "pt": ["conduzir", "liderar", "levar"]},
  {"de": "sprechen", "en": ["speak", "talk"], "fr": ["parler"], "pt": ["falar", "conversar"]},
  {"de": "bringen", "en": ["bring", "take"], "fr": ["apporter", "amener"], "pt": ["trazer", "levar"]},
  {"de": "leben", "en": ["live"], "fr": ["vivre"], "pt": ["viver", "morar"]},
  {"de": "fahren", "en": ["drive", "go", "travel"], "fr": ["conduire", "aller", "rouler"], "pt": ["dirigir", "ir", "viajar"]},
  {"de": "meinen", "en": ["mean", "think"], "fr": ["penser", "vouloir dire"], "pt": ["achar", "querer dizer", "pensar"]},
  {"de": "fragen", "en": ["ask"], "fr": ["demander"], "pt": ["perguntar"]},
  {"de": "kennen", "en": ["know", "be familiar with"], "fr": ["connaître"], "pt": ["conhecer"]},
  {"de": "gelten", "en": ["be valid", "count", "apply"], "fr": ["valoir", "être valable"], "pt": ["valer", "ser válido"]},
  {"de": "stellen", "en": ["put", "place", "set"], "fr": ["mettre", "poser"], "pt": ["colocar", "pôr"]},
  {"de": "spielen", "en": ["play"], "fr": ["jouer"], "pt": ["jogar", "brincar", "tocar"]},
  {"de": "arbeiten", "en": ["work"], "fr": ["travailler"], "pt": ["trabalhar"]},
  {"de": "brauchen", "en": ["need"], "fr": ["avoir besoin"], "pt": ["precisar", "necessitar"]},
  {"de": "folgen", "en": ["follow"], "fr": ["suivre"], "pt": ["seguir"]},
  {"de": "lernen", "en": ["learn"], "fr": ["apprendre"], "pt": ["aprender"]},
  {"de": "verstehen", "en": ["understand"], "fr": ["comprendre"], "pt": ["entender", "compreender"]},
  {"de": "setzen", "en": ["set", "put", "sit"], "fr": ["mettre", "poser", "asseoir"], "pt": ["colocar", "pôr", "sentar"]},
  {"de": "bekommen", "en": ["get", "receive"], "fr": ["recevoir", "obtenir"], "pt": ["receber", "obter", "ganhar"]},
  {"de": "beginnen", "en": ["begin", "start"], "fr": ["commencer"], "pt": ["começar", "iniciar"]},
  {"de": "erzählen", "en": ["tell", "narrate"], "fr": ["raconter"], "pt": ["contar", "narrar"]},
  {"de": "versuchen", "en": ["try", "attempt"], "fr": ["essayer", "tenter"], "pt": ["tentar", "experimentar"]},
  {"de": "schreiben", "en": ["write"], "fr": ["écrire"], "pt": ["escrever"]},
  {"de": "laufen", "en": ["run", "walk"], "fr": ["courir", "marcher"], "pt": ["correr", "andar"]},
  {"de": "erklären", "en": ["explain"], "fr": ["expliquer"], "pt": ["explicar"]},
  {"de": "gehören", "en": ["belong"], "fr": ["appartenir"], "pt": ["pertencer"]},
  {"de": "gewinnen", "en": ["win", "gain"], "fr": ["gagner"], "pt": ["ganhar", "vencer"]},
  {"de": "tragen", "en": ["carry", "wear"], "fr": ["porter"], "pt": ["carregar", "vestir", "usar"]},
  {"de": "scheinen", "en": ["seem", "shine", "appear"], "fr": ["sembler", "briller", "paraître"], "pt": ["parecer", "brilhar"]},
  {"de": "essen", "en": ["eat"], "fr": ["manger"], "pt": ["comer"]},
  {"de": "lesen", "en": ["read"], "fr": ["lire"], "pt": ["ler"]},
  {"de": "hören", "en": ["hear", "listen"], "fr": ["entendre", "écouter"], "pt": ["ouvir", "escutar"]},
  {"de": "warten", "en": ["wait"], "fr": ["attendre"], "pt": ["esperar", "aguardar"]},
  {"de": "suchen", "en": ["search", "look for", "seek"], "fr": ["chercher"], "pt": ["procurar", "buscar"]},
  {"de": "treffen", "en": ["meet", "hit"], "fr": ["rencontrer", "toucher"], "pt": ["encontrar", "atingir", "acertar"]},
  {"de": "schaffen", "en": ["manage", "create", "accomplish"], "fr": ["réussir", "créer", "arriver à"], "pt": ["conseguir", "criar", "realizar"]},
  {"de": "legen", "en": ["lay", "put"], "fr": ["poser", "mettre"], "pt": ["colocar", "pôr", "deitar"]},
  {"de": "ziehen", "en": ["pull", "move", "draw"], "fr": ["tirer", "déménager"], "pt": ["puxar", "mudar-se", "tirar"]},
  {"de": "handeln", "en": ["act", "deal", "trade"], "fr": ["agir", "négocier"], "pt": ["agir", "negociar", "tratar"]},
  {"de": "erreichen", "en": ["reach", "achieve"], "fr": ["atteindre"], "pt": ["alcançar", "atingir"]},
  {"de": "erhalten", "en": ["receive", "maintain", "preserve"], "fr": ["recevoir", "maintenir"], "pt": ["receber", "manter", "obter"]},
  {"de": "entwickeln", "en": ["develop"], "fr": ["développer"], "pt": ["desenvolver"]},
  {"de": "erkennen", "en": ["recognize", "realize"], "fr": ["reconnaître"], "pt": ["reconhecer", "perceber"]},
  {"de": "entstehen", "en": ["arise", "emerge", "come about"], "fr": ["naître", "apparaître", "se former"], "pt": ["surgir", "originar-se", "formar-se"]},
  {"de": "bestehen", "en": ["exist", "consist", "pass", "insist"], "fr": ["exister", "consister", "réussir"], "pt": ["existir", "consistir", "passar"]},
  {"de": "entscheiden", "en": ["decide"], "fr": ["décider"], "pt": ["decidir"]},
  {"de": "öffnen", "en": ["open"], "fr": ["ouvrir"], "pt": ["abrir"]},
  {"de": "schließen", "en": ["close", "conclude", "shut"], "fr": ["fermer", "conclure"], "pt": ["fechar", "concluir"]},
  {"de": "treten", "en": ["step", "kick", "tread"], "fr": ["marcher", "donner un coup de pied"], "pt": ["pisar", "chutar", "entrar"]},
  {"de": "hoffen", "en": ["hope"], "fr": ["espérer"], "pt": ["esperar", "torcer"]},
  {"de": "fühlen", "en": ["feel"], "fr": ["sentir", "ressentir"], "pt": ["sentir"]},
  {"de": "verlieren", "en": ["lose"], "fr": ["perdre"], "pt": ["perder"]},
  {"de": "kaufen", "en": ["buy"], "fr": ["acheter"], "pt": ["comprar"]},
  {"de": "vergessen", "en": ["forget"], "fr": ["oublier"], "pt": ["esquecer"]},
  {"de": "verlassen", "en": ["leave", "abandon"], "fr": ["quitter", "abandonner"], "pt": ["deixar", "abandonar"]},
  {"de": "erwarten", "en": ["expect", "await"], "fr": ["attendre", "s'attendre"], "pt": ["esperar", "aguardar"]},
  {"de": "erscheinen", "en": ["appear", "seem"], "fr": ["apparaître", "paraître"], "pt": ["aparecer", "surgir"]},
  {"de": "erfahren", "en": ["find out", "experience", "learn"], "fr": ["apprendre", "éprouver"], "pt": ["descobrir", "saber", "experimentar"]},
  {"de": "bilden", "en": ["form", "educate", "make up"], "fr": ["former"], "pt": ["formar", "educar"]},
  {"de": "darstellen", "en": ["represent", "depict", "portray"], "fr": ["représenter", "dépeindre"], "pt": ["representar", "retratar"]},
  {"de": "beschreiben", "en": ["describe"], "fr": ["décrire"], "pt": ["descrever"]},
  {"de": "wählen", "en": ["choose", "vote", "dial"], "fr": ["choisir", "voter"], "pt": ["escolher", "votar", "discar"]},
  {"de": "reden", "en": ["talk", "speak"], "fr": ["parler"], "pt": ["falar", "conversar"]},
  {"de": "schauen", "en": ["look", "watch"], "fr": ["regarder"], "pt": ["olhar"]},
  {"de": "holen", "en": ["fetch", "get"], "fr": ["aller chercher", "chercher"], "pt": ["buscar", "pegar", "ir buscar"]},
  {"de": "sitzen", "en": ["sit", "be sitting"], "fr": ["être assis", "s'asseoir"], "pt": ["estar sentado", "sentar"]},
  {"de": "trinken", "en": ["drink"], "fr": ["boire"], "pt": ["beber"]},
  {"de": "werfen", "en": ["throw", "cast"], "fr": ["jeter", "lancer"], "pt": ["jogar", "atirar", "lançar"]},
  {"de": "wachsen", "en": ["grow"], "fr": ["grandir", "pousser", "croître"], "pt": ["crescer"]},
  {"de": "zahlen", "en": ["pay"], "fr": ["payer"], "pt": ["pagar"]},
  {"de": "rechnen", "en": ["calculate", "count on", "reckon"], "fr": ["calculer", "compter"], "pt": ["calcular", "contar"]},
  {"de": "reichen", "en": ["be enough", "suffice", "pass", "reach"], "fr": ["suffire", "passer", "tendre"], "pt": ["bastar", "chegar", "passar"]},
  {"de": "sorgen", "en": ["care", "provide", "worry"], "fr": ["s'occuper", "veiller", "se soucier"], "pt": ["cuidar", "garantir", "preocupar-se"]},
  {"de": "verbinden", "en": ["connect", "combine", "link"], "fr": ["relier", "connecter", "unir"], "pt": ["conectar", "ligar", "unir"]},
  {"de": "verwenden", "en": ["use", "employ"], "fr": ["utiliser", "employer"], "pt": ["usar", "utilizar", "empregar"]},
  {"de": "bewegen", "en": ["move"], "fr": ["bouger", "déplacer", "émouvoir"], "pt": ["mover", "mexer"]},
  {"de": "beobachten", "en": ["observe", "watch"], "fr": ["observer"], "pt": ["observar"]},
  {"de": "betrachten", "en": ["consider", "view", "regard"], "fr": ["considérer", "regarder"], "pt": ["considerar", "observar"]},
  {"de": "entdecken", "en": ["discover"], "fr": ["découvrir"], "pt": ["descobrir"]},
  {"de": "erinnern", "en": ["remember", "remind"], "fr": ["se rappeler", "se souvenir", "rappeler"], "pt": ["lembrar", "recordar"]},
  {"de": "erlauben", "en": ["allow", "permit"], "fr": ["permettre", "autoriser"], "pt": ["permitir"]},
  {"de": "gelingen", "en": ["succeed", "work out"], "fr": ["réussir"], "pt": ["dar certo", "conseguir", "ter êxito"]},
  {"de": "passieren", "en": ["happen", "occur"], "fr": ["arriver", "se passer"], "pt": ["acontecer", "ocorrer", "passar"]},
  {"de": "ändern", "en": ["change", "alter", "modify"], "fr": ["changer", "modifier"], "pt": ["mudar", "alterar"]},
  {"de": "steigen", "en": ["rise", "climb", "increase"], "fr": ["monter", "augmenter"], "pt": ["subir", "aumentar"]},
  {"de": "unterstützen", "en": ["support"], "fr": ["soutenir", "appuyer"], "pt": ["apoiar", "dar suporte", "sustentar"]},
  {"de": "kämpfen", "en": ["fight", "struggle"], "fr": ["combattre", "se battre", "lutter"], "pt": ["lutar", "combater"]},
  {"de": "sterben", "en": ["die"], "fr": ["mourir"], "pt": ["morrer"]},
  {"de": "vorstellen", "en": ["introduce", "imagine", "present"], "fr": ["présenter", "imaginer"], "pt": ["apresentar", "imaginar"]},
  {"de": "funktionieren", "en": ["work", "function"], "fr": ["fonctionner", "marcher"], "pt": ["funcionar"]},
  {"de": "interessieren", "en": ["interest", "be interested"], "fr": ["intéresser"], "pt": ["interessar"]},
  {"de": "studieren", "en": ["study"], "fr": ["étudier"], "pt": ["estudar"]},
  {"de": "schlafen", "en": ["sleep"], "fr": ["dormir"], "pt": ["dormir"]},
  {"de": "kochen", "en": ["cook"], "fr": ["cuisiner"], "pt": ["cozinhar"]},
  {"de": "waschen", "en": ["wash"], "fr": ["laver"], "pt": ["lavar"]},
  {"de": "tanzen", "en": ["dance"], "fr": ["danser"], "pt": ["dançar"]},
  {"de": "singen", "en": ["sing"], "fr": ["chanter"], "pt": ["cantar"]},
  {"de": "springen", "en": ["jump"], "fr": ["sauter"], "pt": ["saltar"]},
  {"de": "fallen", "en": ["fall"], "fr": ["tomber"], "pt": ["cair"]},
  {"de": "packen", "en": ["pack", "grab"], "fr": ["emballer", "saisir"], "pt": ["empacotar", "agarrar"]},
  {"de": "wecken", "en": ["wake", "wake up"], "fr": ["réveiller"], "pt": ["acordar"]},
  {"de": "teilen", "en": ["share", "divide"], "fr": ["partager", "diviser"], "pt": ["partilhar", "dividir"]},
  {"de": "danken", "en": ["thank"], "fr": ["remercier"], "pt": ["agradecer"]},
  {"de": "entschuldigen", "en": ["excuse", "apologise"], "fr": ["excuser", "s'excuser"], "pt": ["desculpar"]},
  {"de": "unterhalten", "en": ["entertain", "chat"], "fr": ["divertir", "converser"], "pt": ["entreter", "conversar"]},
  {"de": "lieben", "en": ["love"], "fr": ["aimer"], "pt": ["amar"]},
  {"de": "hassen", "en": ["hate"], "fr": ["haïr", "détester"], "pt": ["odiar"]},
  {"de": "träumen", "en": ["dream"], "fr": ["rêver"], "pt": ["sonhar"]},
  {"de": "riechen", "en": ["smell"], "fr": ["sentir"], "pt": ["cheirar"]},
  {"de": "schmecken", "en": ["taste"], "fr": ["goûter", "avoir le goût"], "pt": ["saborear", "ter sabor"]},
  {"de": "verkaufen", "en": ["sell"], "fr": ["vendre"], "pt": ["vender"]},
  {"de": "bauen", "en": ["build", "construct"], "fr": ["construire", "bâtir"], "pt": ["construir"]},
  {"de": "fliegen", "en": ["fly"], "fr": ["voler"], "pt": ["voar"]},
  {"de": "schwimmen", "en": ["swim"], "fr": ["nager"], "pt": ["nadar"]},
  {"de": "schreien", "en": ["shout", "scream"], "fr": ["crier"], "pt": ["gritar"]},
  {"de": "schicken", "en": ["send"], "fr": ["envoyer"], "pt": ["enviar"]},
  {"de": "rufen", "en": ["call", "shout"], "fr": ["appeler", "crier"], "pt": ["chamar", "gritar"]},
  {"de": "messen", "en": ["measure"], "fr": ["mesurer"], "pt": ["medir"]},
  {"de": "drücken", "en": ["press", "push"], "fr": ["appuyer", "presser"], "pt": ["pressionar", "apertar"]},
  {"de": "lächeln", "en": ["smile"], "fr": ["sourire"], "pt": ["sorrir"]},
  {"de": "weinen", "en": ["cry", "weep"], "fr": ["pleurer"], "pt": ["chorar"]},
  {"de": "genießen", "en": ["enjoy"], "fr": ["profiter de", "savourer"], "pt": ["aproveitar", "desfrutar"]},
];
